name: Flutter CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Get Dependencies
        run: flutter pub get

      - name: Create .env.development file
        run: |
          echo -e "MAPS_API_KEY=${{ secrets.SUPABASE_URL }}" > .env.development
      - name: Create .env file
        run: |
          echo -e "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > .env

      - name: Build APK
        run: flutter build apk
